### ISSUE TITLE
Conversion matrix from RGB to XYZ is a little imprecise

### ISSUE THREAD

**Issue by keithw** [vinaypillai/ac-colors#1]
sRGB 0xFFFFFF should map to (X, Y, Z = 95.05, 100.00, 108.90). Right now it's mapping to XYZ(95.047, 100.000, 108.883).

This can be achieved by using the matrix given in the sRGB specifications (e.g. formula F.7 of https://www.sis.se/api/document/preview/562720/ ).

It looks like https://github.com/vinaypillai/ac-colors/blob/2933744e6b7cec221ef02d0e7673a5ce93b1df37/index.js#L249-L251 is a popular (but slightly imprecise) approximation of this matrix and that's leading to the slightly off XYZ values. (The matrix on Wikipedia's sRGB article also comes close but doesn't quite nail it either...)

**Comment by vinaypillai** [comment]
Thanks for the reference, latest release should fix the problem
