### ISSUE TITLE
Weird issues with values of colors

### ISSUE THREAD

**Issue by chrlsbr** [vinaypillai/ac-colors#10]
Hello,

I'm not really good with JavaScript so I may have missed something, but I've got issues with some values of colors changing when I declare new variables. I think it's easier to show an example:

```javascript
let white0 = new Color({"color":[255,255,255]});
let white = new Color({"color":"#ffffff","type":"hex"});
console.log(white0._rgb);
console.log(white._rgb);

let primaryBlue1 = new Color({"color":"#263542","type":"hex"});
//let primaryBlue1CTW = Color.contrastRatio(primaryBlue1, white);

console.log(white0._rgb);
console.log(white._rgb);
```

This outputs:

> [ 255, 255, 255 ]
> [ 255, 255, 255 ]
> [ 255, 255, 255 ]
> [ 255, 255, 255 ]

But if I uncomment the primaryBlue1CTW line, then the output changes:

```javascript
let white0 = new Color({"color":[255,255,255]});
let white = new Color({"color":"#ffffff","type":"hex"});
console.log(white0._rgb);
console.log(white._rgb);

let primaryBlue1 = new Color({"color":"#263542","type":"hex"});
let primaryBlue1CTW = Color.contrastRatio(primaryBlue1, white);

console.log(white0._rgb);
console.log(white._rgb);
```

output:

> [ 255, 255, 255 ]
> [ 255, 255, 255 ]
> [ 255, 255, 255 ]
> [ 1, 1, 1]

If I had more hex colors to the list, the values of all of them start to be irrational. Not sure what's the issue here. Does anyone have an idea?

**Comment by chrlsbr** [comment]
Here's an example of wrong values, especially with RGB and contrast calculation:
https://codesandbox.io/s/zen-glitter-8og5n?file=/src/index.js

**Comment by vinaypillai** [comment]
Ah that's an interesting problem. I'll try to take a closer look at it and get it fixed later this week.
